name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Containerized Build
        run: docker build --file Dockerfile --tag marcgeld/bredbandskollen:$(date +%s) .
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      
